config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users
  root 'movies#index'

  resources :movies
  # resources :comments
  resources :accounts do 
    resources :playlists 
  end 

  resources :accounts do
    member do
      get :add_comment
      get :add_comment_to_account
    end
  end

  # scope'movies/:movie_id', as: 'movie' do
  #
  #   resources :comments, only: [:new, :create]
  # end

  resources :movies do
    resources :comments
  end

end

app/models/account.rb
class Account < ApplicationRecord

  belongs_to :user
  has_many :comments 
  has_many :playlists 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :comments
  belongs_to :playlist
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :account
  has_many :movies 
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :accounts
  has_many :comments
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :set_account, only: [:show, :edit, :update]

  def index
    @accounts = current_user.accounts
  end

  def show
    @comments = current_user.comments
  end

  def new
    @account = Account.new
  end

  def edit
  end

  def create
    @account = current_user.accounts.new(account_params)
    if @account.save
      redirect_to accounts_path
    else
      render :new
    end
  end

  def udpate
    if @account.update(account_params)
      redirect_to accounts_path
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
  end

  private
    def set_account
      #don't just users Account.find(params[:id]) or you would be able to view
      #others accounts
      @account = current_user.accounts
    end

    def account_params
      params.require(:account).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user! 
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_movie
  before_action :set_comment, only: [:show, :edit, :update, :destroy ]

  def new
    @comment = Comment.new
  end

  def show
  end

  def edit
  end

  def create
    @comment = @movie.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end

    def destroy
      @comment.destroy
      redirect_to movie_comments_path
    end
  end

  private

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    def set_comment
        @comment = Comment.find(params[:id])
      end


    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :update, :edit, :destroy]

  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)
    
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  private
    
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :duration, :genre, :description, :trailer)
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :update, :edit, :destroy]
  before_action :set_p_movie_id, only: [:add_movie_to_playlist] 
  before_action :set_account 
  def index
    @playlists = Playlist.all
  end

  def add_movie 
    @movies = Movie.all 
    @playlist = Playlist.find(params[:id])
  end 

  def add_movie_to_playlist
    @movies = Movie.all
    @playlist.playlist_movies = "#{@playlist.playlist_movies}, #{@movie.id}"
    @array =  @playlist.playlist_movies
    @a = @array.split(",")
     @playlist.playlist_movies = @a.join(",")
    @playlist.save
    render :show
  end

  def show
    @movies = Movie.all
    @array = @playlist.playlist_movies
    @playlist.save
  end

  def new
    @playlist = Playlist.new
  end

  def edit
  end

  def create
    @playlist = @account.playlist.new(playlist_params)
   
    if @playlist.save
      redirect_to account_playlists_path(@account)
    else
      render :new
    end
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist
    else
      render :edit
    end
  end

  def destroy
    @playlist.destroy
    redirect_to playlists_index_path
  end

  private
    def set_p_movie_id
      @playlist = Playlist.find(params[:p])
      @movie = Movie.find(params[:m])
    end
     def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    def playlist_params
      params.require(:playlist).permit(:title)
    end

    def set_account 
      @account = current_user.accounts
    end 
end 

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

app/views/accounts/index.html.erb
<div class=container>
  <h2>Welcome: <%= current_user.first_name %>
  </h2>
  <hr />
    <%= link_to "See Comments", account_path(@accounts) %>
    <%= link_to "Playlists", account_playlists_path(@accounts) %>
</div>
<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/accounts/new.html.erb
<h1>Accounts#new</h1>
<p>Find me in app/views/accounts/new.html.erb</p>

app/views/accounts/show.html.erb
<% @comments.each do |comment| %>
    <div>
      <%= comment.body %>
    </div>

<% end %>

<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/comments/_comment.html.erb
<hr />

<p><strong><%= comment.body %></strong></p>
</hr>

app/views/comments/edit.html.erb
<div class="container"><h1>Edit A comment</h1>
<%= form_for [@movie, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.submit %>
<% end %>
</div>
<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/comments/new.html.erb
<div class="container"><h1>Add A comment</h1>
<%= form_for [@movie, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.submit %>
<% end %>
</div>
<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper red accent-4">
    <a href="/" class="brand-logo">uToob</a>
    <ul class="right hide-on-med-and-down">
    <li><%= link_to 'Movies', root_path%></li>
    <li><%= link_to 'Upload', new_movie_path %></li>
    <li><%= link_to 'Account', accounts_path %></li>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>uToob</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>


  </head>

  <body class=>

    <%= render 'layouts/navbar' %>
      <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />

  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <br />

  <%= f.label :duration %>
  <%= f.text_field :duration %>
  <br />

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br />

  <%= f.label :trailer %>
  <%= f.text_area :trailer %>
  <br />

  <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

app/views/movies/index.html.erb
<h2 class=center>Movies</h2>

<div class=container>
  <% @movies.each do |movie| %>
  <div>
  <%= link_to movie.title, movie %> 
  </div>
  <% end %>
</div>

<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/movies/new.html.erb
<div class="container">
<h2> Add new movie </h2>
<%= render 'form' %>  
</div>

<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/movies/show.html.erb
<div class="container">
<h2><%= @movie.title %></h2>

<iframe src= "<%= @movie.trailer %> " height=768 width=1024></iframe>

<h6>Genre: <%= @movie.genre %> Duration: <%= @movie.duration %></h6>
<a href="<%= @movie.description %>"> IMDB</a>
<br>
<%= link_to 'Add Comment', new_movie_comment_path(@movie) %>
<h5>Comments</h5>
<% @movie.comments.each do |comment| %>
  <%= render 'comments/comment', { comment: comment } %>
  <%= link_to 'Edit Comment', edit_movie_comment_path(@movie, comment) %>
  <%= link_to 'Delete', [@movie, @comment], method: :delete%>
  <% end %>
<hr />

</div>

<div class="right-align">
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete%>
</div>

app/views/playlists/_form.html.erb
  <%= form_for @playlist do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, required: true, autofocus: true %>
    <%= f.submit %>
  <% end %>

app/views/playlists/edit.html.erb
<h1>Playlists#edit</h1>
<p>Find me in app/views/playlists/edit.html.erb</p>

app/views/playlists/index.html.erb
<h2 class=center>Playlists</h2>

<div class=container>
  <div class="right white-text btn med red accent-4">
    <%= link_to 'Add a new playlist', new_account_playlist_path(@account) %>
  </div>
  <% @playlists.each do |playlist| %>
    <div>
      <%= link_to playlist.title, playlist %>
    </div>
    <% end %>
    
</div>

app/views/playlists/new.html.erb
<%= render 'form' %>

app/views/playlists/show.html.erb
<h1>Playlists#show</h1>
<p>Find me in app/views/playlists/show.html.erb</p>